export default function(server) {
  server.logging = true;

  let precambian = server.create('supereon', { name: 'Precambian', start: -4600, end: -541 });
    server.create('eon', { name: 'Hadean', start: -4600, end: -4000, supereon: precambian });
    let archean = server.create('eon', { name: 'Archean', start: -4000, end: -2500, supereon: precambian });
      server.create('era', { name: 'Eoarchean', start: -4000, end: -3600, eon: archean });
      server.create('era', { name: 'Paleoarchean', start: -3600, end: -3200, eon: archean });
      server.create('era', { name: 'Mesoarchean', start: -3200, end: -2800, eon: archean });
      server.create('era', { name: 'Neoarchean', start: -2800, end: -2500, eon: archean });
    let proterozoic = server.create('eon', { name: 'Proterozoic', start: -2500, end: -541, supereon: precambian });
      let paleoproterozoic = server.create('era', { name: 'Paleoproterozoic', start: -2500, end: -1600, eon: proterozoic });
        server.create('period', { name: 'Siderian', start: -2500, end: -2300, era: paleoproterozoic });
        server.create('period', { name: 'Rhyacian', start: -2300, end: -2050, era: paleoproterozoic });
        server.create('period', { name: 'Orosirian', start: -2050, end: -1800, era: paleoproterozoic });
        server.create('period', { name: 'Statherian', start: -1800, end: -1600, era: paleoproterozoic });
      let mesoproterozoic = server.create('era', { name: 'Mesoproterozoic', start: -1600, end: -1000, eon: proterozoic });
        server.create('period', { name: 'Calymmian', start: -1600, end: -1400, era: mesoproterozoic });
        server.create('period', { name: 'Ectasian', start: -1400, end: -1200, era: mesoproterozoic });
        server.create('period', { name: 'Stenian', start: -1200, end: -1000, era: mesoproterozoic });
      let neoproterozoic = server.create('era', { name: 'Neoproterozoic', start: -1000, end: -541, eon: proterozoic });
        server.create('period', { name: 'Tonian', start: -1000, end: -720, era: neoproterozoic });
        server.create('period', { name: 'Cryogenian', start: -720, end: -635, era: neoproterozoic });
        server.create('period', { name: 'Ediacaran', start: -635, end: -541, era: neoproterozoic });

  let postcambian = server.create('supereon', { name: 'Postcambian', start: -541, end: 0 });
    let phanerozoic = server.create('eon', { name: 'Phanerozoic', start: -541, end: 0, supereon: postcambian });
      let paleozoic = server.create('era', { name: 'Paleozoic', start: -541, end: -251.902, eon: phanerozoic });
        server.create('period', { name: 'Cambrian', start: -541, end: -485.4, era: paleozoic });
        server.create('period', { name: 'Ordovician', start: -485.4, end: -443.8, era: paleozoic });
        server.create('period', { name: 'Silurian', start: -443.8, end: -419.2, era: paleozoic });
        server.create('period', { name: 'Devonian', start: -419.2, end: -358.9, era: paleozoic });
        server.create('period', { name: 'Carboniferous', start: -358.9, end: -298.9, era: paleozoic });
        server.create('period', { name: 'Permian', start: -298.9, end: -251.902, era: paleozoic });
        server.create('period', { name: 'Permian', start: -298.9, end: -251.902, era: paleozoic });
      let mesozoic = server.create('era', { name: 'Mesozoic', start: -251.902, end: -66, eon: phanerozoic });
        server.create('period', { name: 'Triassic', start: -251.902, end: -201.3, era: mesozoic });
        server.create('period', { name: 'Jurassic', start: -201.3, end: -145, era: mesozoic });
        server.create('period', { name: 'Cretaceous', start: -145, end: -66, era: mesozoic });
      let cenozoic = server.create('era', { name: 'Cenozoic', start: -66, end: 0, eon: phanerozoic });
        let paleogene = server.create('period', { name: 'Paleogene', start: -66, end: -23.03, era: cenozoic });
          let paleocene = server.create('epoch', { name: 'Paleocene', start: -66, end: -56, period: paleogene });
            server.create('age', { name: 'Danian', start: -66, end: -61.6, epoch: paleocene });
            server.create('age', { name: 'Selandian', start: -61.6, end: -59.2, epoch: paleocene });
            server.create('age', { name: 'Thanetian', start: -59.2, end: -5, epoch: paleocene });
          let eocene =  server.create('epoch', { name: 'Eocene', start: -56, end: -33.9, period: paleogene });
            server.create('age', { name: 'Ypresian', start: -56, end: -47.8, epoch: eocene });
            server.create('age', { name: 'Lutetian', start: -47.8, end: -41.2, epoch: eocene });
            server.create('age', { name: 'Bartonian', start: -41.2, end: -37.8, epoch: eocene });
            server.create('age', { name: 'Priabonian', start: -37.8, end: -33.9, epoch: eocene });
          let oligocene = server.create('epoch', { name: 'Oligocene', start: -33.9, end: -23.03, period: paleogene });
            server.create('age', { name: 'Rupelian', start: -33.9, end: -27.82, epoch: oligocene });
            server.create('age', { name: 'Chattian', start: -27.82, end: -23.03, epoch: oligocene });
        let neogene = server.create('period', { name: 'Neogene', start: -23.03, end: -2.58, era: cenozoic });
          let miocene = server.create('epoch', { name: 'Miocene', start: -23.03, end: -5.333, period: neogene });
            server.create('age', { name: 'Aquitanian', start: -23.03, end: -20.44, epoch: miocene });
            server.create('age', { name: 'Burdigalian', start: -20.44, end: -15.97, epoch:  miocene });
            server.create('age', { name: 'Langhian', start: -15.97, end: -13.82, epoch:  miocene });
            server.create('age', { name: 'Serravallian', start: -13.82, end: -11.63, epoch:  miocene });
            server.create('age', { name: 'Tortonian', start: -11.63, end: -7.246, epoch:  miocene });
            server.create('age', { name: 'Messinian', start: -7.246, end: -5.333, epoch:  miocene });
          let pliocene = server.create('epoch', { name: 'Pliocene', start: -5.333, end: -2.58, period: neogene });
            server.create('age', { name: 'Zanclean', start: -5.333, end: -3.600, epoch: pliocene });
            server.create('age', { name: 'Piacenzian', start: -3.600, end: -2.58, epoch: pliocene });
        let quaternary = server.create('period', { name: 'Quaternary', start: -2.58, end: 0, era: cenozoic });
          let pleistocene = server.create('epoch', { name: 'Pleistocene', start: -2.58, end: -1.80, period: quaternary });
            server.create('age', { name: 'Gelasian', start: -2.58, end: -1.80, epoch: pleistocene });
            server.create('age', { name: 'Calabrian', start: -1.80, end: -0.781, epoch: pleistocene });
            server.create('age', { name: 'Chibanian', start: -0.781, end: -0.126, epoch: pleistocene });
            server.create('age', { name: 'Tarantian', start: -0.126, end: -0.0117, epoch: pleistocene });
          let holocene = server.create('epoch', { name: 'Holocene', start: -0.0117, end: 0, period: quaternary });
            server.create('age', { name: 'Preboreal', dateUnits: 'ka', start: -10.3, end: -9, epoch: holocene });
            server.create('age', { name: 'Boreal', dateUnits: 'ka', start: -9, end: -7.5, epoch: holocene });
            server.create('age', { name: 'Atlantic', dateUnits: 'ka', start: -7.5, end: -5, epoch: holocene });
            server.create('age', { name: 'Subboreal', dateUnits: 'ka', start: -5, end: -2.5, epoch: holocene });
            server.create('age', { name: 'Subatlantic', dateUnits: 'ka', start: -2.5, end: 0, epoch: holocene });
}
